# Docker Compose for Redis (Celery broker/backend)
# Usage: docker-compose -f docker-compose.redis.yml up -d

version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: sequoia_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

volumes:
  redis_data:
    driver: local